# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netstatus_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='location',
        ),
        migrations.AddField(
            model_name='device',
            name='location_x',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='location_y',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=100),
            preserve_default=False,
        ),
    ]
